public class MyCalculation {
        public static void Mysum(){
           integer i=20, j=10, Result=0 ;
            Result = i + j ;
            system.debug('sumResult' + Result);
        }
        public static void Mysub(){
         integer i=20, j=10, Result=0 ;
            Result = i - j ;
            system.debug('subResult' + Result);
        }
        public static void Mymul(){
            integer i=20, j=10, Result=0 ;
            Result = i * j ;
            system.debug('mulResult' + Result);
    }
    public static void Mydiv(){
     integer i=20, j=10, Result=0 ;
            Result = i / j ;
            system.debug('divResult' + Result);
    }
	public static void Mychange(){
	system.debug('Hello');
}
  public static void Mychange1(){
	system.debug('Hello111');
}
}